[package]
name = "bpf-fs-events-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
bpf-fs-events = { path = "../bpf-fs-events" }
bpf-fs-events-sock = { path = "../bpf-fs-events-sock" }
clap = { version = "4", features = ["derive"] }
ctrlc = "3.4.4"
